### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by Jerome1337** [d0x2f/CloverMerge#6]
When I try to use `clover-merge` command, I get an error 

```
fatal error: Uncaught Error: Class 'd0x2f\CloverMerge\Invocation' not found in /code/vendor/php/d0x2f/clover-merge/clover-merge:6
Stack trace:
#0 {main}
  thrown in /code/vendor/php/d0x2f/clover-merge/clover-merge on line 6
```

The `Invocation` class seem not to be found.

**Comment by d0x2f** [comment]
Am I right in guessing you've cloned the repo and attempted to run the command?

For this to work you will need to run `composer install` first, that will install each of the dependencies after which the command will work.

I'll add a description to the read me.

**Comment by Jerome1337** [comment]
@d0x2f I added it as a dependency of my project.
This should directly work or doing the `composer install` implicitly, no ?

**Comment by d0x2f** [comment]
It works okay for me (see the screenshot bellow).
Is there anything else about your setup that you think might affect things?

![image](https://user-images.githubusercontent.com/8149130/50459363-89b09c80-09be-11e9-9769-e703315b4219.png)

**Comment by Jerome1337** [comment]
I found why.

All my composer packages are inside `vendor/php/*` the require once was wrong

```
require_once 'vendor/autoload.php';
```
I needed to change it 

```
require_once 'vendor/php/autoload.php';
```

It would be great to autodetect the `autoload` emplacement but I don't know how ATM.

**Comment by d0x2f** [comment]
Ah I see, glad you figured it out.
