### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by shyim** [d0x2f/CloverMerge#8]
Hey,

we have multiple testsuites in PHPUnit and I want to merge the result coverage file. This tool looks like not working with new PHP versions anymore. 

I could make an PR if wanted

**Comment by d0x2f** [comment]
Hi, I still use this in many pipelines.
Could you create an issue for the specific problems you're facing?

And of course I'm happy to accept PRs, that'd be much appreciated.
